### ISSUE TITLE
review: FinalizationGroup.prototype.cleanupSome: is `callback` required or optional?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-weakrefs#111]
(editor review per #110)

If it's required, it seems like it should be part of the `length` - ie, not surrounded by brackets in the signature.

If it's optional, then it seems like it shouldn't throw a TypeError if it's `undefined` (just like `unregisterToken` in `register`).

https://tc39.github.io/proposal-weakrefs/#sec-cleanup-finalization-group implies that it can, in fact, be `undefined`, ie that it's optional.

**Comment by littledan** [comment]
Good catch. The intention is for it to be optional. The IsCallable check should also allow it to be undefined.
