### ISSUE TITLE
Add WeakRef.prototype.constructor

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-weakrefs#131]
the WeakRef.prototype.constructor is missing in the proposed specs, add it for consistency with other built-in constructors?

**Comment by leobalter** [comment]
also, the text should be no more than:

`The initial value of WeakRef.prototype.constructor is the intrinsic object %WeakRef%.`

**Comment by mhofman** [comment]
@erights mentions in https://github.com/tc39/proposal-weakrefs/issues/55#issuecomment-444534867 that the `.constructor` property can only appear in appendix B.

**Comment by leobalter** [comment]
All right, so at least I hope this leads me to the right direction as I'll spend time authoring tests the way it's currently specified then.

**Comment by leobalter** [comment]
> Both WeakRef and FinalizationGroup must only appear on the System object

@erights please clarify if FinializationGroup.prototype.constructor should not exist as well?

The proposed specs currently have:

- no WeakRef.prototype.constructor
- a [defined FinalizationGroup.prototype.constructor](https://tc39.github.io/proposal-weakrefs/#sec-finalization-group.prototype.constructor)

Is that correct?

**Comment by littledan** [comment]
Following the conclusion of the "Annex B reform" topic, I think we should retain the `FinalizationGroup.prototype.constructor` property as is, and add an inline normative optional `WeakRef.prototype.constructor` property of %WeakRef%. I'll make a PR for this.
