### ISSUE TITLE
Editorial: Shoud FinalizationGroup.prototype specify it does not have a [[Target]] internal?

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-weakrefs#137]
Currently, FinalizationGroup.prototype is specified to not have a [[Target]] slot, but maybe it should say it does not have the internal slots from an instance of FinalizationGroup?
 
https://tc39.es/proposal-weakrefs/#sec-properties-of-the-finalization-group-prototype-object

**Comment by littledan** [comment]
Good point; we should probably be talking about [[Cells]] here. PRs welcome.
