### ISSUE TITLE
Editorial nit pick: FinalizationGroup.prototype.register steps consistency

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-weakrefs#138]
This is a nit pick:

For steps consistency, please change the order on steps 3 and 4, so it makes the steps consistent with unregister, checking the this before the arguments.

This won't cause a real observable issue other than precedence on the error messages.

[FinalizationGroup.prototype.register](https://tc39.es/proposal-weakrefs/#sec-finalization-group.prototype.register)

```diff
- 3. If Type(target) is not Object, throw a TypeError exception.
- 4. If finalizationGroup does not have a [[Cells]] internal slot, throw a TypeError exception.
+ 3. If finalizationGroup does not have a [[Cells]] internal slot, throw a TypeError exception.
+ 4. If Type(target) is not Object, throw a TypeError exception.
```

**Comment by littledan** [comment]
Yep, PRs welcome.
