### ISSUE TITLE
makeWeakCached passes key for unregister token; keys are often primitives

### ISSUE THREAD

**Issue by tjcrowder** [tc39/proposal-weakrefs#189]
`makeWeakCached` passes the object key as the unregister token:

```js
cleanup.register(fresh, key, key);
```

Keys are often primitives, but the unregister token has to be an object (or `undefined` for none).

Options:
1. Pass `fresh`: `cleanup.register(fresh, key, fresh);`
2. Don't pass anything, since `makeWeakCached` never calls `unregister`: `cleanup.register(fresh, key);`

I lean toward not passing anything.

Let me know which you prefer and I'll do a PR. :-)

**Comment by littledan** [comment]
Oops, sounds like we shouldn't pass an unregister token. PR welcome.
