### ISSUE TITLE
What should if WeakFactory.makeCell / makeRef is called after WeakFactory.shutdown?

### ISSUE THREAD

**Issue by marjakh** [tc39/proposal-weakrefs#32]
The current spec doesn't do anything to prevent calling WeakFactory.makeCell or WeakFactory.makeRef after calling WeakFactory.shutdown.

But shutdown has set [[ActiveCells]] to undefined, and then makeCell / makeRef tries to add to it, so that sounds wrong.

If the intention of shutdown is to make the WeakFactory forever unusable, the spec needs to prevent calling makeCell / makeRef somehow (e.g,. set a flag in WeakFactory and throw an error in makeCell / makeRef if the flag is set).

If the intention is to just get rid of the current WeakCells without doing cleanup for them, the spec needs to reset the members in such a way that it remains usable. (The function could be called e.g., "clear()" in that case.)

**Comment by littledan** [comment]
There is no longer a shutdown method, so this issue no longer seems relevant.
