### ISSUE TITLE
WeakRefs require that each gc-able object be associated with a root realm

### ISSUE THREAD

**Issue by erights** [tc39/proposal-weakrefs#35]
See https://github.com/tc39/ecma262/issues/1333#issuecomment-432655824

The WeakRef spec itself needs to be updated to clearly specify *root realm* rather than *realm* (which would include compartments).

**Comment by littledan** [comment]
Seems like this will not be possible, per https://github.com/tc39/proposal-weakrefs/issues/52#issuecomment-483060724 . Let's follow up on this issue in #52, which discusses the same thing.
