### ISSUE TITLE
WeakCell.prototype.clear(): step 5 could be a little more clear

### ISSUE THREAD

**Issue by fitzgen** [tc39/proposal-weakrefs#43]
```
5. If factory is not undefined.
     i.   Remove O from factory.[[ActiveCells]].
     ii.  Set O.[[Target]] to undefined.
     iii. Set O.[[Factory]] to undefined.
     iv.  Set O.[[Holdings]] to undefined.
```

First, it seems that there should be some sort of assertion/check that `factory` is a `WeakFactory` object. Yes, it seems it will always be such an object if it isn't `undefined`, but I think things could be a bit more clear in the spec text here.

Second, there should probably be some sort of check for if `factory.[[ActiveCells]]` is a list and is not `undefined`, since `WeakFactory.prototype.shutdown` can set it to `undefined`. Again, seems pretty obvious what is the intended behavior, but the spec could be made a bit more clear.

**Comment by littledan** [comment]
I don't think there's anything to change at this point; `[[Cells]]` is always a List, access sites contain either a runtime check or an assertion that `[[Cells]]` is present, and the `shutdown` method was removed.
