### ISSUE TITLE
Should the next method for ReclaimedIterator be on the prototype instead of the object itself?

### ISSUE THREAD

**Issue by fitzgen** [tc39/proposal-weakrefs#48]
Currently the `next` method gets set on the iterator object itself inside `WeakFactoryCleanupJob`:

```
5. Let next be a new built-in function defined in WeakFactoryCleanupIterator next.
6. Perform CreateMethodProperty(iterator, next, next).
```

It seems like the `next` method should be on the prototype, since all objects want to share the same method. In fact, this is what map and set iterators do: https://tc39.github.io/ecma262/#sec-%mapiteratorprototype%.next

**Comment by gsathya** [comment]
The new spec fixes it: https://weakrefs.netlify.com/#sec-%finalizationgroupcleanupiterator%.next
