### ISSUE TITLE
FinalizationGroup.prototype.register should throw if Type(target) is not Object

### ISSUE THREAD

**Issue by mhofman** [tc39/proposal-weakrefs#68]
Currently the spec doesn't mandate `FinalizationGroup.prototype.register` to throw if Type(target) is not Object.
This would cause the value to be recorded in a Record cell, but since non-objects can't be collected, they will stay in the `Cells` list of the FinalizationGroup indefinitely.

Also, this causes the `[[Target]]` slot to be inconsistent between Cell Records and `WeakRef` objects, that do check for Type(target) to be an Object.

**Comment by gsathya** [comment]
Currently, V8 allows `target` to be a non `Object`, which is why I spec'd it this way. But, I think you're right that we shouldn't allow this.
