### ISSUE TITLE
Example wrong in merged pull request

### ISSUE THREAD

**Issue by erights** [tc39/proposal-weakrefs#98]
I made comments on a recent merged pull request https://github.com/tc39/proposal-weakrefs/pull/95 . I'm filing this as an issue because I've seen comments on merged PRs be unnoticed.

> What is getPtr?

> This example is wrong. y is a strong pointer to the object. While y is live, the object it cannot be collected. Therefore, derefing a weakref to it, even in a later turn, must give back the object, so long as y is live. Since y and z both participate in the comparison, clearly y is still live at that point

**Comment by wingo** [comment]
I think the `what is getptr` question is adequately answered there and there is no error to my knowledge.

Your other comment is correct and I will take a look tomorrow.
